modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/AlephInfinity1/ForgeBlock/issues" #optional
[[mods]] #mandatory
modId="forgeblock" #mandatory
version="${file.jarVersion}" #mandatory
displayName="ForgeBlock Mod" #mandatory

# updateJSONURL="http://myurl.me/" #optional #Removed / commencted since there isnt a website for this.

# displayURL="http://example.com/" #optional #Removed / commencted since there isnt a website for this.

# logoFile="examplemod.png" #optional Might come back, not really needed

credits="AlephInfinity1, Si1kn" #optional

authors="AlephInfinity1, Si1kn" #optional

description='''
This is a WIP recreation of Hypixel's popular gamemode, SkyBlock.

If you find any bugs / issues please open one at the github link:
https://github.com/AlephInfinity1/ForgeBlock/issues
'''